package:
  name: vartriage
  version: '0.2.2'

source:
  git_rev: v0.2.2
  git_url: git@github.com:micknudsen/vartriage.git

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

about:
  home: https://github.com/micknudsen/vartriage
